/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameControl from "./script/GameControl"
import HomeControl from "./script/HomeControl"
import LoginControl from "./script/LoginControl"
import MatchControl from "./script/MatchControl"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/GameControl.js",GameControl);
		reg("script/HomeControl.js",HomeControl);
		reg("script/LoginControl.js",LoginControl);
		reg("script/MatchControl.js",MatchControl);
    }
}
GameConfig.width = 1280;
GameConfig.height = 720;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "none";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "main/login.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = true;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
